repos = {
    # Hackathons
    "ai-agent-hackathon": r"C:\k26rahul\Code\GitHub\Hackathons\ai-agent-hackathon",
    "cricket-hackathon-2023": r"C:\k26rahul\Code\GitHub\Hackathons\cricket-hackathon-2023",
    "space-hackathon": r"C:\k26rahul\Code\GitHub\Hackathons\space-hackathon",
    "microsoft-ai-odyssey": r"C:\k26rahul\Code\GitHub\Hackathons\microsoft-ai-odyssey",
    "studymate": r"C:\k26rahul\Code\GitHub\Hackathons\studymate",
    "rythmfit-hack-o-pitch-2.0": r"C:\k26rahul\Code\GitHub\Hackathons\rythmfit-hack-o-pitch-2.0",
    "violence-detection-hackathon": r"C:\k26rahul\Code\GitHub\Hackathons\violence-detection-hackathon",
    "pixelmind-ai-hackathon": r"C:\k26rahul\Code\GitHub\Hackathons\pixelmind-ai-hackathon",

    # Web Development
    "ai-rpg-chat": r"C:\k26rahul\Code\GitHub\Web-Development\ai-rpg-chat",
    "auth-system-flask": r"C:\k26rahul\Code\GitHub\Web-Development\auth-system-flask",
    "bs-grade-calculator": r"C:\k26rahul\Code\GitHub\Web-Development\bs-grade-calculator",
    "event-emitter-lib": r"C:\k26rahul\Code\GitHub\Web-Development\event-emitter-lib",
    "expense-tracker-react": r"C:\k26rahul\Code\GitHub\Web-Development\expense-tracker-react",
    "html-projects": r"C:\k26rahul\Code\GitHub\Web-Development\html-projects",
    "inventory-management-system": r"C:\k26rahul\Code\GitHub\Web-Development\inventory-management-system",
    "js-projects": r"C:\k26rahul\Code\GitHub\Web-Development\js-projects",
    "js-projects-2": r"C:\k26rahul\Code\GitHub\Web-Development\js-projects-2",
    "poetrydb-flask-app": r"C:\k26rahul\Code\GitHub\Web-Development\poetrydb-flask-app",
    "poster-catalogue-app": r"C:\k26rahul\Code\GitHub\Web-Development\poster-catalogue-app",
    "fastapi-postgresql-basics": r"C:\k26rahul\Code\GitHub\Web-Development\fastapi-postgresql-basics",
    "react-egghead-course": r"C:\k26rahul\Code\GitHub\Web-Development\react-egghead-course",
    "react-egghead-course-2": r"C:\k26rahul\Code\GitHub\Web-Development\react-egghead-course-2",
    "tic-tac-toe-vanilla-js-2025": r"C:\k26rahul\Code\GitHub\Web-Development\tic-tac-toe-vanilla-js-2025",
    "tic-tac-toe-react": r"C:\k26rahul\Code\GitHub\Web-Development\tic-tac-toe-react",
    "tic-tac-toe-vanilla-js": r"C:\k26rahul\Code\GitHub\Web-Development\tic-tac-toe-vanilla-js",
    "plotly-vector-visualizer": r"C:\k26rahul\Code\GitHub\Web-Development\plotly-vector-visualizer",
    "remotion-story-video": r"C:\k26rahul\Code\GitHub\Web-Development\remotion-story-video",
    "weather-app-react": r"C:\k26rahul\Code\GitHub\Web-Development\weather-app-react",

    # Machine Learning
    "boston-housing-price-prediction": r"C:\k26rahul\Code\GitHub\Machine-Learning\boston-housing-price-prediction",
    "deep-learning-march-2024": r"C:\k26rahul\Code\GitHub\Machine-Learning\deep-learning-march-2024",
    "machine-learning-april-2023": r"C:\k26rahul\Code\GitHub\Machine-Learning\machine-learning-april-2023",
    "machine-learning-kylie-ying": r"C:\k26rahul\Code\GitHub\Machine-Learning\machine-learning-kylie-ying",
    "machine-learning-april-2025": r"C:\k26rahul\Code\GitHub\Machine-Learning\machine-learning-april-2025",
    "machine-learning-march-2024": r"C:\k26rahul\Code\GitHub\Machine-Learning\machine-learning-march-2024",
    "ml-projects-siddhardhan": r"C:\k26rahul\Code\GitHub\Machine-Learning\ml-projects-siddhardhan",
    "ipl2023-powerplay-score-prediction": r"C:\k26rahul\Code\GitHub\Machine-Learning\ipl2023-powerplay-score-prediction",

    # DSA
    "codeforces-december-2023": r"C:\k26rahul\Code\GitHub\DSA\codeforces-december-2023",
    "dsa-cp": r"C:\k26rahul\Code\GitHub\DSA\dsa-cp",
    "dsa-java-march-2024": r"C:\k26rahul\Code\GitHub\DSA\dsa-java-march-2024",
    "dsa-java-september-2024": r"C:\k26rahul\Code\GitHub\DSA\dsa-java-september-2024",
    "mosh-ultimate-dsa-java": r"C:\k26rahul\Code\GitHub\DSA\mosh-ultimate-dsa-java",

    # IITM
    "mad1-coursework": r"C:\k26rahul\Code\GitHub\IITM\mad1-coursework",
    "mad1-course-website": r"C:\k26rahul\Code\GitHub\IITM\mad1-course-website",
    "mad2-coursework": r"C:\k26rahul\Code\GitHub\IITM\mad2-coursework",
    "machine-learning-techniques": r"C:\k26rahul\Code\GitHub\IITM\machine-learning-techniques",
    "dbms-t3-2023": r"C:\k26rahul\Code\GitHub\IITM\dbms-t3-2023",
    "dbms-t1-2024": r"C:\k26rahul\Code\GitHub\IITM\dbms-t1-2024",
    "dbms-t2-2024": r"C:\k26rahul\Code\GitHub\IITM\dbms-t2-2024",
    "mad1-project": r"C:\k26rahul\Code\GitHub\IITM\mad1-project",
    "mad1-project-skeleton": r"C:\k26rahul\Code\GitHub\IITM\mad1-project-skeleton",
    "mad1-project-prototype": r"C:\k26rahul\Code\GitHub\IITM\mad1-project-prototype",
    "flask-sqlalchemy-template": r"C:\k26rahul\Code\GitHub\IITM\flask-sqlalchemy-template",
    "mad2-project": r"C:\k26rahul\Code\GitHub\IITM\mad2-project",
    "mad2-project-skeleton": r"C:\k26rahul\Code\GitHub\IITM\mad2-project-skeleton",
    "java-t1-2024": r"C:\k26rahul\Code\GitHub\IITM\java-t1-2024",
    "java-t1-2025": r"C:\k26rahul\Code\GitHub\IITM\java-t1-2025",
    "java-t2-2025": r"C:\k26rahul\Code\GitHub\IITM\java-t2-2025",
    "pdsa-t1-2024": r"C:\k26rahul\Code\GitHub\IITM\pdsa-t1-2024",
    "pdsa-t2-2024": r"C:\k26rahul\Code\GitHub\IITM\pdsa-t2-2024",
    "python-t2-2023": r"C:\k26rahul\Code\GitHub\IITM\python-t2-2023",
    "python-t1-2024": r"C:\k26rahul\Code\GitHub\IITM\python-t1-2024",
    "python-oppe1-t3-2023": r"C:\k26rahul\Code\GitHub\IITM\python-oppe1-t3-2023",
    "python-oppe2-t3-2023": r"C:\k26rahul\Code\GitHub\IITM\python-oppe2-t3-2023",

    # Others
    "k26rahul": r"C:\k26rahul\Code\GitHub\Others\k26rahul",
    "playground-2024": r"C:\k26rahul\Code\GitHub\Others\playground-2024",
    "playground-2025": r"C:\k26rahul\Code\GitHub\Others\playground-2025",
    "yt-channel-downloader": r"C:\k26rahul\Code\GitHub\Others\yt-channel-downloader",

    # Work (New Repos)
    "bdm-assignments": r"C:\k26rahul\Code\Work\bdm-assignments",
    "github-management": r"C:\k26rahul\Code\Work\github-management",
    "leetcode": r"C:\k26rahul\Code\Work\leetcode",
    "probability-dist-viz": r"C:\k26rahul\Code\Work\probability-dist-viz",
    "python-t3-2025": r"C:\k26rahul\Code\Work\python-t3-2025",
    "simplilearn-auto-watcher": r"C:\k26rahul\Code\Work\simplilearn-auto-watcher",
    "sql-practice": r"C:\k26rahul\Code\Work\sql-practice",
    "stories-by-maa": r"C:\k26rahul\Code\Work\stories-by-maa"
}
